# Created by ofortin on 2023/11/20
FLAGS = -g -Wall 

01 : src/01.c
	gcc $(FLAGS) src/01.c -o build/01

02 : src/02.c
	gcc $(FLAGS) src/02.c -o build/02

03 : src/03.c
	gcc $(FLAGS) src/03.c -o build/03

all : 01 02 03

